#!/bin/sh
. /etc/s6-overlay/s6-rc.d/.config-init

mkdir -p /run/sshd

ssh-keygen -A 2>/dev/null

cat > /etc/ssh/sshd_config.d/99-container.conf << EOF
Port 22
PermitRootLogin yes
PasswordAuthentication yes
UsePAM no
EOF

ROOT_PASSWORD="${SSH_ROOT_PASSWORD:-wazuh}"
echo "root:${ROOT_PASSWORD}" | chpasswd

exec /usr/sbin/sshd -D -e
